config/routes.rb
Rails.application.routes.draw do
  # get 'projects/index'
  devise_for :users
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    post :import, on: :member
    # resources :words
    post :add_language, on: :member
    resources :words, only: [:index, :create]
  end
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_languages
  has_many :languages, through: :project_languages
  has_many :words
  belongs_to :default_language, class_name: 'Language'
end

app/models/project_language.rb
class ProjectLanguage < ApplicationRecord
  belongs_to :project
  belongs_to :language
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :word
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/models/word.rb
class Word < ApplicationRecord
  extend ActsAsTree::TreeView
  extend ActsAsTree::TreeWalker
  acts_as_tree
  belongs_to :project
  has_many :translations
  has_many :default_translations, class_name: 'Translation'

  def self.to_yaml(options = {})
    YAML.generate(options) do |yaml|
      yaml << column_values
      all.each do |word|
        yaml << word.attributes.values_at(*column_values)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, only: %i[edit update destroy show import add_language]
  def index
    @projects = Project.where(user_id: current_user.id).order('name ASC')
  end

  def new
    @project = Project.new(user_id: current_user.id)
  end

  def show; end

  def import
    content = YAML.load_file(params[:project][:locales].path)
    puts_tree(content, @project)
    # puts(content)
  end

  def add_language
    @project = ProjectLanguage.where(project_id: params[:id], language_id: params[:project_languages][:language_id]).first_or_create
  end

  def edit; end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def puts_tree(content, project, parent_id = nil)
    content.each do |key, value|
      word = Word.new(word: key, project_id: project.id, parent_id: parent_id)
      word.save!
      puts_tree(value, project, word.id) if value.is_a?(Hash)
      save_translation(project.default_language_id, word.id, value) unless value.is_a?(Hash)
    end
  end

  def save_translation(language_id, word_id, text)
    Translation.find_or_create_by(language_id: language_id, word_id: word_id) do |t|
      t.text = text
    end
  end

  def project_params
    params.require(:project).permit(:name, :default_language_id)
  end

  def find_project
    @project = Project.find_by(id: params[:id], user_id: current_user.id)
  end
end

app/controllers/words_controller.rb
class WordsController < BaseController
  before_action :find_project

  def index
    @per_page = 20
    # @words = Word.find_by_sql(['select w.id, w.word, t.text,
    #   tt.text as translated_text, w.parent_id
    # From words w
    # Left join translations t on t.word_id = w.id And t.language_id = ?
    # Left join translations tt on tt.word_id = w.id And tt.language_id = ?
    # Where w.project_id = ?
    # Order by w.id ASC', @project.default_language_id, params[:language_id],
    #                            @project.id])
    @words = Word.includes(:default_translations).where(['words.project_id = ? and translations.language_id = ?', @project.id, @project.default_language_id]).references(:default_translations)
    respond_to do |format|
      format.html
      format.yaml { send_data @words.to_yaml }
      format.xls # { send_data @words.to_csv, mime_type: Mime::Type.lookup('application/xls') }
    end
  end

  def create
    @tr = Translation.find_by(language_id: params[:word][:language_id], word_id:
                                                       params[:word][:word_id])
    if @tr
      @tr.text = params[:word][:text]
    else
      @tr = Translation.new(translation_params)
    end
    @tr.save!
    render js: "alert('saved')"
  end

  private

  def find_project
    @project = Project.find_by(id: params[:project_id],
                               user_id: current_user.id)
  end

  def translation_params
    params.require(:word).permit(:word_id, :language_id, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= "Localization"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    .container
      - if user_signed_in?
        = render partial: "shared/top_header"

      .row.top-padding
        = render partial: "shared/flash_messages", flash: flash
        %br/
        = yield
        %br/
        %br/
        %br/

    = yield :footer_js

app/views/projects/edit.html.erb
<%= form_for @project, url: project_path(@project), html: {method: :put} do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.select(:default_language_id, Language.all.collect {|p| [ p.name, p.id ] })%>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
 <%= link_to 'back', projects_path %>

app/views/projects/index.html.haml
%h2= 'Projects list'

.row
  = link_to 'Add new project', new_project_path, class: 'btn btn-primary'
%br/
%br/
.row
  %table.table.table-striped.table-hover
    %tr
      %th #
      %th Name
      %th Default language
      %th Enable Languages
      %th Actions


    - @projects.each do |project|
      %tr
        %td= project.id
        %td= link_to project.name, project_path(project)
        %td= project.default_language.name
        %td
          %ol
            - project.languages.each do |l|
              %li= link_to l.name, project_words_path(project, language_id: l.id)
        %td
          = link_to 'Edit', edit_project_path(project), class: 'btn btn-info btn-sm'
          &nbsp;
          = link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

app/views/projects/new.html.haml
%h2= 'Add new project'

%br/
.row
  = form_for :project, url: projects_path, class: 'form' do |f|
    .form-group
      = f.label :name
      = f.text_field :name
    .form-group
      = f.select(:default_language_id, Language.all.collect {|p| [ p.name, p.id ] })

    %button.btn.btn-info{ type: 'submit' } Submit


%br/
%br/
.row
  = link_to 'Back', projects_path, class: 'btn btn-primary'

app/views/projects/show.html.haml
%h2= 'Import words'
%br/
%br/

.row
  = form_for :project, url: import_project_path(@project), html: {method: :post} do |f|
    .form-group
      =f.label :content
      = f.file_field :locales
    .form-group
      %button.btn.btn-info{ type: 'submit' } Submit

%h2= 'Add language'
%br/
%br/
.row
  = form_for :project_languages, url: add_language_project_path(@project), html: {method: :post} do |f|
    .form-group
      = f.label :add_language
    .form-group
      = f.select(:language_id, Language.all.collect {|p| [ p.name, p.id ] })
    .form-group
      %button.btn.btn-info{ type: 'submit' } Submit

%br/
%br/
.row
  = link_to 'Back', projects_path, class: 'btn btn-primary'

app/views/shared/_top_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{ type: 'button', 'data-toggle' => "collapse", 'data-target' => "#bs-example-navbar-collapse-1", 'aria-expanded' => "false" }
          %span.sr-only 'Toggle navigation'
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        %a.navbar-brand Localization

      .collapse.navbar-collapse#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav
          %li.active
            = link_to 'Projects', projects_path
        %ul.nav.navbar-nav.navbar-right
          %li= link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/words/index.html.erb
<%=link_to 'new project', new_project_path%>

<table border="1px">
<tr>
  <th>Word Key</th>
  <th>Defaul Language</th>
  <th>Translation</th>
  <th>Save</th>
</tr>
<% - i = 0 %>
<%- @words.walk_tree do |word,l|%>
  <% - i=i+1 %>
  <%= form_for :word, url: project_words_path(@project.id), remote: true do |f| %>
    <%= f.hidden_field 'word_id', value: word.id %>
    <%= f.hidden_field :language_id, value: params[:language_id] %>
    <tr>

      <td><%= (' &nbsp; &nbsp; ' * l.to_i).html_safe %><%= word.word %></td>

    </tr>


  <% end %>
<% end %>
</table>
 <%= link_to 'back', projects_path %>
 <p>
   Download:
   <%= link_to "Yaml", project_words_path(format: "yaml") %>
   <%= link_to "Excel", project_words_path(format: "xls") %>
 </p>

app/views/words/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Word Id</Data></Cell>
        <Cell><Data ss:Type="String">Defaul Language</Data></Cell>
        <Cell><Data ss:Type="String">Translation</Data></Cell>

      </Row>
    <% @words.each do |word| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= word.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= word.word %></Data></Cell>
        <Cell><Data ss:Type="String"><%= word.translations %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>